#!/bin/sh
# Writes Soapstone/BuildInfo.lua (git-ignored) with the checkout's branch,
# short commit and commit date, so /soap version can show which build is
# running. The hooks in .githooks/ run this after checkout, commit, merge
# and rebase; run it by hand if the file is missing:
#
#     sh tools/buildinfo.sh
#
# Enable the hooks once per clone:  git config core.hooksPath .githooks

root=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
[ -d "$root/Soapstone" ] || exit 0

branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
[ "$branch" = "HEAD" ] && branch="detached"
commit=$(git rev-parse --short HEAD 2>/dev/null)
date=$(git log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M' 2>/dev/null)

# Lua string safety: escape backslashes and double quotes.
escape() { printf '%s' "$1" | sed 's/[\\"]/\\&/g'; }

cat > "$root/Soapstone/BuildInfo.lua" <<EOF
-- Generated by tools/buildinfo.sh (git hooks); not tracked. Shown by /soap version.
local _, ns = ...
ns.BUILD = { branch = "$(escape "$branch")", commit = "$(escape "$commit")", date = "$(escape "$date")" }
EOF
